CREATE TABLE IF NOT EXISTS [PrivilegedUser] (
	[Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	[UserType] INTEGER NOT NULL,
	[UserId] VARCHAR NOT NULL,

	FOREIGN KEY ([UserType]) REFERENCES [Protocol] ([Id])
);
