CREATE TABLE IF NOT EXISTS [DefaultRoom] (
	[Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	[RoomType] INTEGER NOT NULL,
	[RoomId] VARCHAR NOT NULL,

	FOREIGN KEY ([RoomType]) REFERENCES [Protocol] ([Id])
);
